spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/preproject
    username: root
    password: root1234!
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  jwt:
    access:
      plus-hour: 1   # 1시간
    refresh:
      plus-hour: 168   # 24*7 7일
    secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
