name: Deploy To EC2

on:
  push:
    branches:
      - main
      - dev


jobs:
  CICD:
    runs-on: ubuntu-latest
    steps:
      - name: SSH(원격 접속)으로 EC2에 접속하기

        uses: appleboy/ssh-action@v1.0.3
        env:
          APPLICATION_YAML: ${{ secrets.APPLICATION_YAML }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          envs: APPLICATION_YAML,S3_ACCESS_KEY,S3_SECRET_KEY,S3_REGION,S3_BUCKET_NAME

          script_stop:  true
          script: |
            cd /home/ubuntu/popcorn
            rm -rf src/main/resources/application.yml  
            git pull origin dev
            echo "$APPLICATION_YAML" > src/main/resources/application.yml
            chmod +x ./gradlew 
            ./gradlew clean build
            sudo fuser -k -n tcp 8080 || true   
            nohup java -jar build/libs/*SNAPSHOT.jar > ./output.log 2>&1 &
